"""Pure deterministic contracts and engine for the HeatSafe replay."""

from .engine import (
    advance_minute,
    advance_tick,
    hourly_summary,
    initialize_state,
    load_zone_priors,
    run_full_day,
    weather_at,
)
from .models import (
    AcclimatizationClass,
    DriverState,
    DriverStatus,
    InterventionState,
    InterventionStatus,
    OrderEvent,
    OrderEventType,
    OrderState,
    OrderStatus,
    PauseControl,
    ScoringProjection,
    SimulationState,
    TickResult,
    WeatherState,
    ZonePrior,
    ZoneProjection,
)
from .randomness import (
    DeterministicRandom,
    canonical_checksum,
    canonical_json,
    stable_int,
)
from .scenario import (
    ScenarioFixture,
    ScenarioValidationError,
    load_scenario,
)
from .repository import (
    BigQuerySimulationRepository,
    InMemorySimulationRepository,
    LeaseConflict,
    PersistedTick,
    SimulationRepositoryError,
    SimulationRun,
    TickLease,
)
from .control import (
    BigQueryControlWriter,
    ControlValidationError,
    QueuedControl,
    canonical_proposal_checksum,
    validate_control_payload,
)
from .scoring import (
    BigQuerySnapshotScorer,
    DeterministicSnapshotScorer,
    ScoringOutcome,
    SnapshotPrediction,
)
from .transitions import (
    SimulationInvariantError,
    project_scoring,
    project_zones,
    require_driver_transition,
    require_order_transition,
    validate_state,
)
from .realism import (
    RealismAudit,
    audit_full_day,
    load_realism_profile,
    run_realism_audit,
)

__all__ = [
    "AcclimatizationClass",
    "BigQuerySimulationRepository",
    "BigQueryControlWriter",
    "BigQuerySnapshotScorer",
    "ControlValidationError",
    "DeterministicRandom",
    "DeterministicSnapshotScorer",
    "DriverState",
    "DriverStatus",
    "InterventionState",
    "InterventionStatus",
    "InMemorySimulationRepository",
    "LeaseConflict",
    "OrderEvent",
    "OrderEventType",
    "OrderState",
    "OrderStatus",
    "PauseControl",
    "RealismAudit",
    "QueuedControl",
    "ScenarioFixture",
    "ScenarioValidationError",
    "ScoringProjection",
    "ScoringOutcome",
    "SimulationInvariantError",
    "SimulationRepositoryError",
    "SimulationRun",
    "SimulationState",
    "SnapshotPrediction",
    "TickResult",
    "TickLease",
    "PersistedTick",
    "WeatherState",
    "ZonePrior",
    "ZoneProjection",
    "advance_minute",
    "advance_tick",
    "audit_full_day",
    "canonical_checksum",
    "canonical_proposal_checksum",
    "canonical_json",
    "hourly_summary",
    "initialize_state",
    "load_scenario",
    "load_realism_profile",
    "run_realism_audit",
    "load_zone_priors",
    "project_scoring",
    "project_zones",
    "require_driver_transition",
    "require_order_transition",
    "run_full_day",
    "stable_int",
    "validate_state",
    "validate_control_payload",
    "weather_at",
]
